In [62]:
import pandas as pd
import sklearn

In [63]:
df = pd.read_csv('master.csv')
df.head(10)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X

In [64]:
#Quantize columns
df['country'] = df['country'].astype('category').cat.codes
df['age'] = df['age'].astype('category').cat.codes
df['year'] = df['year'].astype('category').cat.codes
df['generation'] = df['generation'].astype('category').cat.codes
df['sex'] = df['sex'].astype('category').cat.codes

#Convert string to int
df['gdp_for_year ($)'] = df['gdp_for_year ($)'].astype('int32')

#Store actual suicide rates into own table
actual_Suicide_rates = df['suicides/100k pop'].values
print(actual_Suicide_rates)

#drop unecessary columns
df = df.drop(columns=['country-year', 'HDI for year', 'suicides_no', 'suicides/100k pop'])

#print
df.head()

KeyError: 'gdp_for_year ($)'

In [ ]:
from sklearn.model_selection import train_test_split

x_raw = df.values

x_train, x_test, y_train, y_test = train_test_split(x_raw, actual_Suicide_rates, test_size=0.2, random_state=42)

In [ ]:
import sklearn
from sklearn.ensemble import RandomForestRegressor

rfRegr = RandomForestRegressor(n_estimators=30, min_samples_leaf=2)
rfRegr.fit(x_train, y_train)